version: '3.9'
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: /run/secrets/connection_string
    secrets:
       - connection_string
    networks:
      - frontnet
      - backnet  
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    environment:
       POSTGRES_PASSWORD: /run/secrets/clave_db
    secrets:
       - clave_db
    networks:
      - backnet

networks:
  frontnet:
    name: externa
  backnet:
    name: interna

secrets:
  clave_db:
    file: clave_db.txt
  connection_string:
    file: connection_string.txt